controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - BaseToLink_1
      - Link_1ToLink_2
      - Link_2ToLink_3
      - Link_3ToLink_4
      - Link_4ToLink_5
      - Link_5ToLink_6